site_name: Materiais de aprendizado Qt
repo_url: https://codeberg.org/herzenschein/materiais-de-aprendizado-qt
repo_name: herzenschein/materiais-de-aprendizado-qt
edit_uri: edit/pages/docs/

nav:
  - sobre.md
  - diferenca.md
  - linguagens.md
  - como-docs.md
  - rota-aprendizado.md
  - canais.md
  - introducoes.md
  - cursos.md
  - livros.md
  - tutoriais.md
  - talks.md
  - qtcore.md
  - qtwidgets.md
  - qtquick.md
  - python.md
  - outros.md
  - contribuindo.md

theme:
  name: material
  language: pt-BR

  features:
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.action.edit

  markdown_extensions:
  - toc:
      permalink: true

  font:
    text: Atkinson Hyperlegible Next
    code: Atkinson Hyperlegible Mono

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
